<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>SciencePotato</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Scripts\Uniit\**" />
    <Compile Remove="Scripts\新文件夹\**" />
    <EmbeddedResource Remove="Scripts\Uniit\**" />
    <EmbeddedResource Remove="Scripts\新文件夹\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scripts\Units\Infrastructure\" />
  </ItemGroup>
</Project>